name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Modules/apigee/proxies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Deploy Shared Flow - Spike Arrest
        working-directory: Modules/apigee/sharedflows/sf-spikearrest
        run: |
          mvn clean install -Peval \
            -Dorg=internship-439613 \
            -Denv=eval \
            -Dbearer="ya29.a0ARGnu0b5YMHOl8MUKUvTo18BTXYfRVsgYwYcb0jEN6yYgfP-GtdW63e_PQhhlQlrg022Qvv0ikbQG7Ru19LFfVfgPAnskwlVbuk8FRTlKFAnn6CVBLCcaOPFFMx_o2n9qhEWmz0Yy-OIJwCIIxqTQPyCkvvEGeW-_FGZtBgdYwl6g_oYT-tu1ZSv80vGKkNo7fvXmF8LEa2p4SfXx8RFyufM2kxXcQoucuZ4b8ZTBZoLdnQIUC17083URvHx9a4uKlei5u2fIRWCJhx79QkGMtDcG_Q4-3onUMZrJeCmZ_Yvp4c8iyOnJcy9KLZhBTjVTaGeNRqi1EAUsxngwVhMcOc1-HgfVcmO57L28TgaCgYKAdsSARESFQHGX2MivTzUS8D1tO06YjgF5lclvA0366" \
            -Dapigee.options=override
      - name: Deploy Shared Flow - Raise Fault
        working-directory: Modules/apigee/sharedflows/sf-raisefault
        run: |
          mvn clean install -Peval \
            -Dorg=internship-439613 \
            -Denv=eval \
            -Dbearer="ya29.a0ARGnu0b5YMHOl8MUKUvTo18BTXYfRVsgYwYcb0jEN6yYgfP-GtdW63e_PQhhlQlrg022Qvv0ikbQG7Ru19LFfVfgPAnskwlVbuk8FRTlKFAnn6CVBLCcaOPFFMx_o2n9qhEWmz0Yy-OIJwCIIxqTQPyCkvvEGeW-_FGZtBgdYwl6g_oYT-tu1ZSv80vGKkNo7fvXmF8LEa2p4SfXx8RFyufM2kxXcQoucuZ4b8ZTBZoLdnQIUC17083URvHx9a4uKlei5u2fIRWCJhx79QkGMtDcG_Q4-3onUMZrJeCmZ_Yvp4c8iyOnJcy9KLZhBTjVTaGeNRqi1EAUsxngwVhMcOc1-HgfVcmO57L28TgaCgYKAdsSARESFQHGX2MivTzUS8D1tO06YjgF5lclvA0366" \
            -Dapigee.options=override
      - name: Build and Deploy Apigee Proxy
        run: |
          mvn clean install -Peval \
            -Dorg=internship-439613 \
            -Denv=eval \
            -Dbearer="ya29.a0ARGnu0b5YMHOl8MUKUvTo18BTXYfRVsgYwYcb0jEN6yYgfP-GtdW63e_PQhhlQlrg022Qvv0ikbQG7Ru19LFfVfgPAnskwlVbuk8FRTlKFAnn6CVBLCcaOPFFMx_o2n9qhEWmz0Yy-OIJwCIIxqTQPyCkvvEGeW-_FGZtBgdYwl6g_oYT-tu1ZSv80vGKkNo7fvXmF8LEa2p4SfXx8RFyufM2kxXcQoucuZ4b8ZTBZoLdnQIUC17083URvHx9a4uKlei5u2fIRWCJhx79QkGMtDcG_Q4-3onUMZrJeCmZ_Yvp4c8iyOnJcy9KLZhBTjVTaGeNRqi1EAUsxngwVhMcOc1-HgfVcmO57L28TgaCgYKAdsSARESFQHGX2MivTzUS8D1tO06YjgF5lclvA0366" \
            -Dapigee.options=override
