name: Deploy Apigee Proxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Modules/apigee/proxies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Deploy Apigee Proxy
        run: |
          mvn clean install -Peval \
            -Dorg=internship-439613 \
            -Denv=eval \
            -Dbearer="ya29.a0ARGnu0amsVZ0HOq0p2vNVLoJ4X6abnoRvW9Hmy1t4V1RuJRaNcjsnaI78J34t6i43tJXxMS0gvxmz9VCGA7r25rgMdQAclS1dB8A6TD4_0KJFU_NWT3CLRqZA1WwCBwX-v0gFZfreOA82UphWCX85ZLPkazV6SU7PFmDHwHqDa6hfLMkRUatMmHdvpXgBlQHKqEx-gpy6Tm9qNHTwAIDTem-ttULZkj5HWbHgfSX-d3jKv85qYWGgxTIagccg2W-A-cvPTdGSdwa2Sk6l3CoD8hZRd7tYNA1q1T9MBWUhrmOB7Qjmmf_AIu8hxE16PrqH0IpQ2TcKwGJk9sexJc8Qrjkg6zfPghNFhxHY1QaCgYKAVsSARESFQHGX2Mi34K9v9yUBmybj59KPb7-SA0366" \
            -Dapigee.options=override
